(TeX-add-style-hook "template"
 (lambda ()
    (TeX-run-style-hooks
     "hyperref"
     "colorlinks"
     "varioref"
     "lastpage"
     "fancyhdr"
     "pict2e"
     "slashbox"
     "float"
     "xcolor"
     "subfigure"
     "url"
     "multirow"
     "array"
     "amssymb"
     "amsmath"
     "amstext"
     "comment"
     "times"
     "graphicx"
     "mathptmx"
     "enumitem"
     "shortlabels"
     "geometry"
     "latex2e"
     "art10"
     "article"
     "10pt")))

